phraseapp:
  access_token: "9980aa276a9e9ef7ab4874f159949820d4fdc61e"
  project_id: "8e8f18031d6f991ac4ee24c00bd2a76c"
  file_format: "strings"
  push:
    sources:
    - file: "./PHraseAppDemo/Base.lproj/Localizable.strings"
      params:
        file_format: strings
        locale_id: en
  pull:
    targets:
    - file: "./PHraseAppDemo/<locale_code>.lproj/Localizable.strings"
      params:
        file_format: strings
